// Banco-semente de temas das categorias fixas.
// Estrutura: TEMAS.categoriasFixas.pesquisa e TEMAS.categoriasFixas.autoconhecimento.
// Atualizado em 2026-08-31 com o banco de perguntas que a Lia trouxe pronto —
// ver CLAUDE.md Secao 1 sobre a mudanca de formato (agora e pergunta em todas as
// categorias fixas, nao so assunto solto / frase-instrucao).
var TEMAS = {
  categoriasFixas: {
    pesquisa: {
      "Moda": [
        "Corset voltou: você usaria? Como combinaria?",
        "Qual tendência você acha linda, mas não usaria?",
        "Jeans skinny voltou: tendência ou retrocesso?",
        "O que faz um look parecer caro?",
        "Você seguiria uma tendência que não combina com você?",
        "Qual peça do seu armário nunca sai de moda?",
        "Tênis combina com qualquer look?",
        "Moda confortável pode ser elegante?",
        "Qual tendência você gostaria de trazer de volta?",
        "Você compraria algo só porque virou tendência?",
        "Look básico precisa ser sem graça?",
        "Qual peça você acha superestimada?",
        "Você prefere tendência ou estilo próprio?",
        "Animal print: clássico ou exagerado?",
        "Você usaria uma peça transparente?",
        "Qual combinação de cores você mais gosta?",
        "Roupa preta sempre deixa o look elegante?",
        "Você acha que acessórios transformam um look?",
        "Qual acessório faz mais diferença para você?",
        "Bolsa pequena é bonita ou pouco prática?",
        "Você usaria uma tendência dos anos 2000?",
        "O que você acha da volta da cintura baixa?",
        "Vestido com tênis: você usaria?",
        "Você acha que moda tem idade?",
        "Existe roupa que não combina com determinada idade?",
        "Você se veste para você ou para os outros?",
        "Qual tendência você nunca entendeu?",
        "Você acha importante conhecer seu estilo?",
        "Como você definiria seu estilo em três palavras?",
        "Você compraria uma peça vintage?",
        "Brechó: economia ou caça ao tesouro?",
        "Você prefere poucas peças boas ou muitas opções?",
        "Fast fashion ainda vale a pena?",
        "Você olha a composição da roupa antes de comprar?",
        "Qual tecido você mais gosta de usar?",
        "Linho amassa demais ou faz parte do charme?",
        "Você usaria roupas de segunda mão?",
        "Uma roupa pode mudar sua confiança?",
        "Você já deixou de usar algo por opinião alheia?",
        "Qual look sempre faz você se sentir bem?",
        "Você repetiria o mesmo look várias vezes?",
        "Repetir roupa ainda é visto como problema?",
        "Você acha que moda influencia comportamento?",
        "O que sua roupa diz sobre você?",
        "Você mudaria seu estilo por uma tendência?",
        "Qual década tem a melhor moda?",
        "Moda masculina influencia seu estilo?",
        "Você acha que uniforme pode ser estiloso?",
        "Qual peça você gostaria de aprender a combinar?",
        "Você usaria uma peça considerada “cafona”?",
        "O que é elegância para você?",
        "Você acha que marcas famosas entregam mais qualidade?",
        "Logo grande: luxo ou ostentação?",
        "Você compraria uma falsificação de grife?",
        "Qual tendência você acha que vai durar?",
        "Qual moda atual você gostaria de esquecer?",
        "Você acha que moda precisa ser confortável?",
        "Qual look você usaria para se sentir poderosa?",
      ],
      "Beleza": [
        "Skincare de 10 passos: necessário ou exagero?",
        "Você acha que maquiagem realça ou transforma?",
        "Qual produto de beleza você não vive sem?",
        "Você usaria maquiagem todos os dias?",
        "Pele perfeita existe ou é filtro?",
        "Você acha que skincare virou obrigação?",
        "Qual tendência de maquiagem você testaria?",
        "Gloss voltou: você gosta?",
        "Batom vermelho combina com qualquer pessoa?",
        "Você prefere maquiagem natural ou marcante?",
        "Sobrancelha muda completamente um rosto?",
        "Você faria uma mudança radical no cabelo?",
        "Cabelo curto: você teria coragem?",
        "Qual corte você nunca faria?",
        "Você acha que cabelo define estilo?",
        "Cabelo natural ou escovado: qual você prefere?",
        "Você usaria uma cor fantasia no cabelo?",
        "Qual tendência de cabelo você traria de volta?",
        "Perfume pode mudar a primeira impressão?",
        "Você escolhe perfume pela estação?",
        "Perfume caro realmente vale mais?",
        "Você prefere um perfume marcante ou discreto?",
        "Qual cheiro lembra sua infância?",
        "Beleza precisa ser cara?",
        "Você compraria um produto viral?",
        "Produto viral funciona mesmo?",
        "Você confia em resenhas de influenciadores?",
        "Você já comprou algo por causa de uma indicação?",
        "Procedimentos estéticos: autocuidado ou pressão?",
        "Você faria preenchimento facial?",
        "Botox: você faria?",
        "Você acha que procedimentos estão banalizados?",
        "Envelhecer naturalmente virou tendência?",
        "Você acha que existe pressão para parecer jovem?",
        "Unhas fazem diferença no visual?",
        "Você prefere unhas discretas ou chamativas?",
        "Qual tendência de unhas você usaria?",
        "Beleza natural é realmente natural?",
        "Você sairia de casa sem maquiagem?",
        "Maquiagem muda sua autoestima?",
        "Você acha que maquiagem é arte?",
        "Qual produto você acha superestimado?",
        "Qual produto barato te surpreendeu?",
        "Você pagaria caro em um cosmético?",
        "Você lê os ingredientes dos produtos?",
        "Beleza sustentável é importante para você?",
        "Você reduziria sua rotina de beleza?",
        "Qual conselho de beleza você não segue?",
        "Você acha que padrões de beleza mudam?",
        "Qual padrão de beleza você gostaria de quebrar?",
        "Beleza tem idade?",
        "Você acha que homens deveriam falar mais sobre beleza?",
        "Qual tendência de beleza você não entende?",
        "Filtro de beleza: diversão ou problema?",
        "Você já se comparou por causa de filtros?",
        "Qual ritual de beleza você mais gosta?",
      ],
      "Entretenimento": [
        "Qual série você assistiria novamente?",
        "Qual filme você acha superestimado?",
        "Qual série merecia uma continuação?",
        "Você prefere filme ou série?",
        "Qual personagem você não suporta?",
        "Qual personagem você defenderia até o fim?",
        "Você abandona uma série quando fica ruim?",
        "Qual final de série mais te decepcionou?",
        "Qual filme todo mundo ama e você não?",
        "Qual série te fez mudar de opinião?",
        "Você prefere assistir sozinho ou acompanhado?",
        "Cinema ainda vale a experiência?",
        "Streaming facilitou ou piorou o entretenimento?",
        "Você assina serviços demais?",
        "Qual streaming você cancelaria hoje?",
        "Reality show é entretenimento ou vício?",
        "Qual reality você acompanharia novamente?",
        "Você gosta de spoilers?",
        "Você pesquisa o final antes de assistir?",
        "Qual gênero você nunca consegue gostar?",
        "Terror realmente te assusta?",
        "Comédia está ficando menos engraçada?",
        "Qual filme te fez chorar?",
        "Qual série te marcou em uma fase da vida?",
        "Você gosta de finais felizes?",
        "Filmes antigos são melhores?",
        "Remakes deveriam existir?",
        "Qual remake você gostaria de ver?",
        "Você acha que Hollywood está sem criatividade?",
        "Sequências quase sempre pioram?",
        "Qual franquia você acompanha até hoje?",
        "Você prefere histórias originais ou adaptações?",
        "Livro adaptado para filme: qual é melhor?",
        "Qual personagem merecia um spin-off?",
        "Você julga uma série pela nota?",
        "Críticas influenciam o que você assiste?",
        "Você confia em recomendações de amigos?",
        "Qual filme você indicaria para qualquer pessoa?",
        "Qual série você indicaria para ninguém?",
        "Você prefere maratonar ou assistir aos poucos?",
        "Episódios semanais são melhores?",
        "Você acha episódios muito longos?",
        "Qual ator sempre te convence?",
        "Qual atriz você sempre acompanha?",
        "Fama transforma artistas em produtos?",
        "Você acha celebridades superexpostas?",
        "Você acompanha a vida pessoal dos artistas?",
        "Você separa artista da obra?",
        "Cancelamento muda o que você assiste?",
        "Você continuaria assistindo alguém cancelado?",
        "Qual celebridade você acha superestimada?",
        "Qual artista merece mais reconhecimento?",
        "O que faz um filme ser inesquecível?",
        "O que faz uma série ser viciante?",
        "Você acha que nostalgia melhora filmes antigos?",
        "Qual tendência do entretenimento você não entende?",
        "Qual conteúdo você gostaria de ver mais?",
      ],
      "Cultura Pop": [
        "Qual fenômeno pop você não entende?",
        "Por que algumas celebridades viram fenômenos?",
        "Fandom aproxima ou afasta as pessoas?",
        "Você já entrou em um fandom por influência?",
        "Qual fandom você acha mais engajado?",
        "Ser fã virou uma identidade?",
        "Você acha que fãs passam dos limites?",
        "Celebridades deveriam se posicionar sobre tudo?",
        "Você acha que a internet cria celebridades rápido demais?",
        "Qual artista você acha subestimado?",
        "Qual artista está superexposto?",
        "Por que algumas músicas viralizam tanto?",
        "TikTok mudou a cultura pop?",
        "Você descobre artistas pelas redes?",
        "Trends estão deixando tudo igual?",
        "Você acha que a nostalgia domina a cultura pop?",
        "Por que os anos 2000 voltaram?",
        "Qual década você acha mais interessante?",
        "Qual tendência pop você traria de volta?",
        "Qual tendência você gostaria de esquecer?",
        "Memes já fazem parte da cultura?",
        "Um meme pode virar negócio?",
        "Influenciadores são celebridades?",
        "Criadores substituíram celebridades tradicionais?",
        "Você acompanha alguém pelo conteúdo ou pela pessoa?",
        "Você acha que fama muda relacionamentos?",
        "Celebridades deveriam ter mais privacidade?",
        "A vida pessoal influencia seu consumo?",
        "Você consegue separar artista e obra?",
        "Boicote realmente funciona?",
        "Cancelamento realmente muda comportamentos?",
        "Você acha que a cultura do cancelamento exagerou?",
        "Por que polêmicas viralizam tanto?",
        "Você já mudou de opinião por causa da internet?",
        "Opiniões populares influenciam você?",
        "Você teria coragem de discordar da maioria?",
        "Por que opiniões extremas ganham atenção?",
        "A internet deixou as pessoas mais críticas?",
        "A internet deixou as pessoas mais intolerantes?",
        "Qual assunto pop domina suas redes?",
        "Você acha que algoritmos moldam seus interesses?",
        "Você consome o que o algoritmo recomenda?",
        "O que está em alta merece sua atenção?",
        "Viralizar virou objetivo demais?",
        "Você acha que todo mundo quer ser influencer?",
        "O que transforma alguém em ícone?",
        "Ícones pop ainda existem?",
        "Qual artista representa sua geração?",
        "Qual fenômeno pop marcou sua adolescência?",
        "Qual fandom você gostaria de conhecer?",
        "Você compraria um produto de um artista favorito?",
        "Merchandising aproxima ou explora fãs?",
        "Shows viraram experiências de consumo?",
        "Você pagaria caro para conhecer seu ídolo?",
        "Qual tendência de cultura pop você não adotaria?",
      ],
      "Música": [
        "Qual música você nunca se cansa de ouvir?",
        "Qual música marcou uma fase da sua vida?",
        "Você prefere descobrir músicas ou ouvir clássicos?",
        "Qual artista você acha subestimado?",
        "Qual artista você acha superestimado?",
        "Você escuta música pelo álbum ou pelo single?",
        "Álbuns ainda fazem sentido hoje?",
        "Você prefere ouvir um álbum inteiro?",
        "Qual álbum você considera perfeito?",
        "Qual música você gostaria de esquecer?",
        "Qual música você defenderia para sempre?",
        "Você julga uma música pela letra?",
        "Letra importa mais que melodia?",
        "Você presta atenção nas letras?",
        "Qual música te faz dançar imediatamente?",
        "Qual música sempre te emociona?",
        "Você escolhe música pelo humor?",
        "Playlist organiza ou limita seu gosto?",
        "Você cria playlists para momentos específicos?",
        "Qual música combina com sua personalidade?",
        "Você acha que música muda seu humor?",
        "Música triste pode fazer bem?",
        "Você ouve música enquanto trabalha?",
        "Você consegue trabalhar sem música?",
        "Show ao vivo vale o preço?",
        "Você prefere festival ou show solo?",
        "Qual artista você gostaria de ver ao vivo?",
        "Você pagaria caro para ver seu artista favorito?",
        "O streaming mudou nossa relação com música?",
        "Você ainda compra música?",
        "Vinil voltou por nostalgia ou experiência?",
        "Você escuta músicas antigas?",
        "Por que músicas antigas estão voltando?",
        "TikTok está mudando a indústria musical?",
        "Viralizar uma música virou mais importante que o álbum?",
        "Você descobre músicas pelo TikTok?",
        "Qual música viral você realmente gostou?",
        "Você acha que artistas lançam músicas demais?",
        "Singles demais prejudicam os álbuns?",
        "Você prefere artistas que somem ou lançam sempre?",
        "O que faz uma música virar hit?",
        "O que faz uma música durar décadas?",
        "Você acha que letras atuais são melhores?",
        "Remakes musicais deveriam existir?",
        "Você gosta de versões acústicas?",
        "Cover pode superar a original?",
        "Você prefere voz ou produção?",
        "Autotune estraga ou transforma a música?",
        "Você acha importante conhecer o artista?",
        "Você separa música e comportamento do artista?",
        "Fãs influenciam a carreira dos artistas?",
        "Qual gênero musical você gostaria de conhecer melhor?",
        "Qual artista mudou sua forma de ouvir música?",
        "Qual música você indicaria para qualquer pessoa?",
      ],
      "Livros": [
        "Qual livro mudou sua forma de pensar?",
        "Qual livro você indicaria para qualquer pessoa?",
        "Qual livro você abandonou sem culpa?",
        "Você termina livros ruins?",
        "Você prefere ficção ou não ficção?",
        "Livro físico ou digital?",
        "Você gosta de reler livros?",
        "Qual livro você gostaria de esquecer?",
        "Qual livro merece mais reconhecimento?",
        "Qual livro é superestimado?",
        "Você escolhe livros pela capa?",
        "A capa influencia sua compra?",
        "Você lê resenhas antes de comprar?",
        "Você confia em recomendações do TikTok?",
        "BookTok melhorou ou piorou a leitura?",
        "Você já comprou um livro por causa de uma trend?",
        "Por que alguns livros viralizam?",
        "Livros deveriam ser adaptados para séries?",
        "Você prefere filme ou livro?",
        "Qual adaptação decepcionou você?",
        "Qual livro merecia uma adaptação?",
        "Você lê vários livros ao mesmo tempo?",
        "Qual seu ritmo ideal de leitura?",
        "Você lê todos os dias?",
        "O que mais atrapalha sua leitura?",
        "Você acha que precisa ler clássicos?",
        "Clássicos ainda são relevantes?",
        "Qual clássico você gostaria de conhecer?",
        "Você acha que livros precisam ensinar algo?",
        "Leitura por prazer ou aprendizado?",
        "Você marca e grifa seus livros?",
        "Você empresta seus livros?",
        "Biblioteca física ainda faz sentido?",
        "Comprar livros virou hobby?",
        "Você acha livros caros?",
        "Sebos são melhores que livrarias?",
        "Você gosta de colecionar livros?",
        "Uma estante cheia significa que você lê?",
        "Você compra mais livros do que consegue ler?",
        "Qual gênero você gostaria de explorar?",
        "Qual gênero você nunca conseguiu gostar?",
        "Você julga um livro pela primeira frase?",
        "O título influencia sua escolha?",
        "Você pesquisa o autor antes de ler?",
        "Você prefere autores nacionais ou estrangeiros?",
        "Qual autor você gostaria de conhecer?",
        "Você consegue separar autor e obra?",
        "Um livro pode mudar uma opinião?",
        "Você já mudou de opinião por causa de um livro?",
        "Qual personagem você defenderia?",
        "Qual personagem você detestaria conhecer?",
        "Você gosta de finais abertos?",
        "Final feliz é realmente necessário?",
        "Qual livro te fez chorar?",
        "Qual livro você levaria para uma ilha deserta?",
      ],
      "Arte": [
        "Arte precisa ser bonita para ser boa?",
        "O que faz algo ser considerado arte?",
        "Você entende arte contemporânea?",
        "Arte contemporânea é genial ou exagerada?",
        "Você gosta de arte abstrata?",
        "Qual obra de arte você gostaria de ter em casa?",
        "Você visitaria uma exposição sozinho?",
        "Museu ainda é interessante para jovens?",
        "Arte deveria ser acessível para todos?",
        "Você pagaria caro por uma obra?",
        "O preço define o valor da arte?",
        "Artista precisa explicar sua obra?",
        "Você gosta de conhecer a história por trás da obra?",
        "Uma obra pode ser interpretada de qualquer forma?",
        "Você já mudou de opinião sobre uma obra?",
        "Qual artista você gostaria de conhecer melhor?",
        "Qual artista você acha subestimado?",
        "Qual artista você acha superestimado?",
        "Você prefere pintura ou fotografia?",
        "Fotografia também é arte?",
        "Design é arte?",
        "Moda é uma forma de arte?",
        "Cinema é arte?",
        "Grafite é arte?",
        "Grafite transforma uma cidade?",
        "Arte urbana deveria ser incentivada?",
        "Você acha que arte precisa provocar?",
        "Uma obra pode ser ofensiva e ainda ser arte?",
        "Você acha que arte deve ter limites?",
        "Censura prejudica a arte?",
        "Arte pode mudar uma sociedade?",
        "Qual obra histórica você gostaria de ver pessoalmente?",
        "Você compraria uma obra de artista desconhecido?",
        "Como você escolheria uma obra para sua casa?",
        "Você teria uma obra muito chamativa em casa?",
        "Minimalismo ou maximalismo na arte?",
        "Você prefere arte realista ou abstrata?",
        "Qual cor você mais gosta em obras?",
        "Você acha que inteligência artificial pode criar arte?",
        "IA substitui artistas?",
        "Você usaria IA para criar uma obra?",
        "Arte digital vale tanto quanto arte física?",
        "NFTs mudaram alguma coisa na arte?",
        "Você acha que arte virou investimento?",
        "Artistas precisam ser bons em redes sociais?",
        "Instagram ajuda artistas a serem descobertos?",
        "Você seguiria um artista pelo processo criativo?",
        "Você gosta de ver bastidores de obras?",
        "Qual museu você gostaria de visitar?",
        "Qual movimento artístico você gostaria de entender?",
        "Uma obra precisa ter significado?",
        "O que faz uma obra ser memorável?",
        "Qual obra você gostaria de perguntar ao artista sobre?",
      ],
      "Psicologia": [
        "Por que procrastinamos mesmo sabendo o que fazer?",
        "Você confunde descanso com preguiça?",
        "Por que é tão difícil dizer não?",
        "Você acha que pensamos demais?",
        "Como você reage às críticas?",
        "Você leva opinião dos outros a sério?",
        "Por que buscamos aprovação?",
        "Você acha que comparação pode ser saudável?",
        "Redes sociais aumentam a comparação?",
        "Por que algumas pessoas precisam agradar todo mundo?",
        "Você acha que perfeccionismo atrapalha?",
        "Por que começamos e não terminamos?",
        "Você se considera disciplinado?",
        "Motivação ou disciplina: o que pesa mais?",
        "Por que hábitos são tão difíceis de manter?",
        "Você acha que rotina melhora a vida?",
        "Como você lida com mudanças?",
        "Por que mudanças assustam tanto?",
        "Você acha que sair da zona de conforto funciona?",
        "Por que temos medo de errar?",
        "Você aprende com seus erros?",
        "Por que algumas críticas doem mais?",
        "Você acha que autoestima pode ser construída?",
        "Autoestima depende da opinião dos outros?",
        "Por que nos sabotamos?",
        "O que realmente significa autossabotagem?",
        "Você acha que pensamos em excesso sobre o futuro?",
        "Por que decisões simples podem ser difíceis?",
        "Você decide mais pela razão ou emoção?",
        "Emoções devem guiar decisões?",
        "Por que perdemos a paciência?",
        "Você acha que inteligência emocional pode ser treinada?",
        "O que diferencia confiança de arrogância?",
        "Você consegue reconhecer seus limites?",
        "Por que temos dificuldade em pedir ajuda?",
        "Pedir ajuda é sinal de fraqueza?",
        "Você acha que pessoas mudam de verdade?",
        "O passado define quem somos?",
        "Por que algumas memórias ficam tão fortes?",
        "Música influencia nossas emoções?",
        "Ambiente influencia nosso comportamento?",
        "Você acha que o ambiente molda hábitos?",
        "Por que algumas pessoas gostam de rotina?",
        "Por que outras odeiam rotina?",
        "Você acha que personalidade muda com o tempo?",
        "Somos mais influenciados pelos outros do que imaginamos?",
        "Por que gostamos de pessoas parecidas conosco?",
        "O que faz alguém parecer confiável?",
        "Primeira impressão importa tanto?",
        "Você acha que julgamos rápido demais?",
        "Por que fofoca é tão interessante?",
        "Curiosidade é uma característica positiva?",
        "Por que buscamos explicações para tudo?",
        "Você acha que pensar positivo ajuda?",
        "Otimismo pode virar negação?",
        "O que significa realmente ter maturidade emocional?",
      ],
      "Em Alta": [
        "Bruna Marquezine e Shawn Mendes: casal real ou só especulação da internet?",
        "Shawn Mendes no Brasil: por que a presença dele virou assunto?",
        "Luísa Sonza noiva: por que anúncios de relacionamento viralizam tanto?",
        "Memphis Depay no Corinthians: por que a permanência gerou tanta repercussão?",
        "“Neysexual”: por que uma expressão sobre Neymar virou meme?",
        "Os memes da Copa de 2026: qual momento mais merecia virar fenômeno?",
        "“A jugar”: por que memes antigos voltam em momentos inesperados?",
        "“Casa do Patrão”: por que esse meme da Copa pegou tanto?",
        "Os momentos inesperados da Copa: o que viraliza mais que o jogo?",
        "Torcedores viram personagens: por que cenas da arquibancada viralizam?",
        "Animais na Copa: por que vídeos de bichos conquistam tanto engajamento?",
        "Marina Sena como Marília Mendonça: o que você espera de uma cinebiografia?",
        "Linkin Park transformando show em filme: você assistiria?",
        "Harry Styles no Brasil: por que shows aumentam tanto as buscas por artistas?",
        "Jimin pedindo para não ser filmado: fãs têm direito de registrar tudo?",
        "BTS e a exposição dos idols: onde deveria estar o limite dos fãs?",
        "Justin Bieber discutindo com paparazzi: celebridade deve reagir ou ignorar?",
        "Ariana Grande e o afastamento dos holofotes: fama cobra um preço alto?",
        "Aparência de artistas vira debate: até onde o público deveria comentar?",
        "Elize Matsunaga voltou ao centro das buscas: por que true crime continua viralizando?",
        "True crime virou entretenimento demais? Onde está o limite?",
        "Crimes reais virando memes: quando a internet passa do ponto?",
        "Augusto Cury viralizou nas redes: fama digital pode mudar uma eleição?",
        "As propostas de Augusto Cury viraram memes: humor ajuda ou prejudica um candidato?",
        "“Ministério da IA”: por que propostas sobre inteligência artificial viralizam?",
        "Drones contra feminicídio: ideia inovadora ou proposta inviável?",
        "Influenciadores em embaixadas: você acha que seria uma boa ideia?",
        "“Nem picanha nem fuzil, eu quero é Rivotril”: por que bordões políticos pegam?",
        "Jingle do Osmarzinho voltou a viralizar: por que músicas antigas ressurgem?",
        "Política virou conteúdo de entretenimento? O que você acha?",
        "Memes políticos funcionam melhor que propaganda tradicional?",
        "Vídeos políticos feitos com IA: você consegue identificar o que é real?",
        "Lula com dez dedos: por que um detalhe visual gerou tanta desinformação?",
        "Deepfake nas eleições: você confiaria em um vídeo político sem checar?",
        "IA nas eleições: deveria existir uma regra para identificar conteúdos manipulados?",
        "Escala 6x1 voltou ao centro das redes: por que esse tema mobiliza tanto?",
        "Fim da escala 6x1: você é a favor ou contra?",
        "“Farmar aura”: por que essa gíria virou obsessão entre jovens?",
        "Galãs do MetrôRio: por que pessoas comuns viralizam tão rápido?",
        "Ovo cozido na chaleira: por que truques banais viram grandes debates?",
        "“Cão CLT”: por que animais com comportamentos humanos viralizam?",
        "Vídeos de filhotes: por que conteúdo fofo continua funcionando tão bem?",
        "Macaco assistindo Reels: o que esse vídeo diz sobre nosso vício em telas?",
        "“Calça da morte”: por que um apelido engraçado pode transformar uma peça em trend?",
        "Sorvete de pudim viralizou: por que comida diferente gera tanta curiosidade?",
        "Ube virou assunto no Brasil: por que ingredientes exóticos entram nas trends?",
        "Produtos virais: você compra pela curiosidade ou pela utilidade?",
        "Uma comida viral precisa ser boa ou só render um bom vídeo?",
        "Trends de comida: por que a gente sente vontade de experimentar o que vê online?",
        "Xuxa no Maracanã: por que despedidas de ícones geram tanta nostalgia?",
        "Xuxa e nostalgia: por que personagens da infância voltam com tanta força?",
        "Shakira recriando um meme antigo: por que celebridades entrando na brincadeira funcionam?",
        "Memes antigos voltando: por que a internet recicla tanto o passado?",
        "“Vampetaço”: por que um meme brasileiro consegue atravessar debates internacionais?",
        "Memes brasileiros: o que faz nosso humor ser tão exportável?",
        "Celebridades flagradas por fãs: conteúdo espontâneo ou invasão de privacidade?",
        "Casais famosos nas redes: por que a vida amorosa gera tanto engajamento?",
        "Um vídeo de poucos segundos pode mudar a imagem de alguém?",
        "Por que uma frase vira meme enquanto outra passa despercebida?",
        "Viralizar significa que algo realmente importa?",
        "Qual desses fenômenos mostra melhor como a internet escolhe seus protagonistas?",
      ],
      "Marketing Digital": [
        "Você acha que todo negócio precisa estar nas redes?",
        "Marketing digital virou obrigação?",
        "Você seguiria uma marca que não produz conteúdo?",
        "O que faz você confiar em uma marca?",
        "Você compra depois de ver conteúdo?",
        "Você já comprou algo pelo Instagram?",
        "Influenciador ainda influencia compras?",
        "Você confia em publis?",
        "Publicidade está ficando previsível?",
        "Você percebe quando uma marca força uma trend?",
        "Toda marca precisa entrar em trends?",
        "Você acha que viralizar vende?",
        "Curtidas ainda importam?",
        "Seguidores realmente significam influência?",
        "O que vale mais: alcance ou vendas?",
        "Você prefere crescer rápido ou construir autoridade?",
        "Conteúdo educativo ainda funciona?",
        "Conteúdo precisa ensinar alguma coisa?",
        "Você acha que conteúdo precisa entreter?",
        "O que faz você parar para assistir?",
        "Por que alguns conteúdos prendem atenção?",
        "Você lê legendas longas?",
        "Carrossel ainda funciona?",
        "Reels são obrigatórios?",
        "Stories ainda vendem?",
        "Você compraria pelo Stories?",
        "Você responde Stories de marcas?",
        "O que faz uma marca parecer humana?",
        "Marcas deveriam mostrar os bastidores?",
        "Você acha que marcas precisam ter personalidade?",
        "Posicionamento diferencia marcas?",
        "Toda marca precisa ter um nicho?",
        "Você compraria de uma marca sem posicionamento?",
        "O que faz uma marca parecer autoridade?",
        "Autoridade vem de seguidores?",
        "Especialista precisa aparecer todos os dias?",
        "Você acha que frequência importa?",
        "Postar todos os dias realmente funciona?",
        "Consistência ou criatividade: qual pesa mais?",
        "Você acha que algoritmo controla tudo?",
        "O algoritmo é realmente o vilão?",
        "Você criaria conteúdo só pensando no algoritmo?",
        "Conteúdo viral pode atrair público errado?",
        "Você acha que conteúdo viral vende pouco?",
        "O que faz alguém compartilhar um conteúdo?",
        "Por que as pessoas salvam conteúdos?",
        "Comentários são mais importantes que curtidas?",
        "Você acha que conteúdo polêmico funciona?",
        "Toda marca deveria se posicionar em assuntos polêmicos?",
        "Você compraria de uma marca com valores diferentes dos seus?",
        "Marketing precisa acompanhar tendências?",
        "Dados ou criatividade: qual vence?",
        "Você acha que IA vai mudar o marketing?",
        "IA ameaça profissionais de marketing?",
        "Marketing digital ficou mais difícil?",
        "Qual estratégia de marketing você gostaria de testar?",
      ],
      "Criação de Conteúdo": [
        "Você precisa ter um nicho para criar conteúdo?",
        "O que você faria se tivesse que postar hoje?",
        "Você acha difícil ter ideias?",
        "De onde vêm boas ideias de conteúdo?",
        "Você anota suas ideias?",
        "Você pesquisaria antes de gravar?",
        "Conteúdo precisa ser original?",
        "Você pode falar sobre algo que já foi dito?",
        "O que faz uma ideia parecer nova?",
        "Você acha que todo conteúdo precisa ensinar?",
        "Conteúdo pessoal pode gerar autoridade?",
        "Você mostraria mais da sua vida?",
        "Você tem medo de se expor?",
        "O que te impede de aparecer?",
        "Você gravaria sem maquiagem?",
        "Você gravaria sem editar?",
        "Vídeo perfeito ou vídeo publicado?",
        "Você acha que câmera boa faz diferença?",
        "Celular é suficiente para criar conteúdo?",
        "Você usaria teleprompter?",
        "Você prefere roteiro ou improviso?",
        "Você consegue falar olhando para a câmera?",
        "O que torna um vídeo interessante?",
        "O começo é mais importante que o final?",
        "Você sabe criar um bom gancho?",
        "Qual tipo de gancho prende sua atenção?",
        "Você usaria uma opinião polêmica para começar?",
        "Você acha que polêmica gera autoridade?",
        "Você salvaria um conteúdo que ensina algo prático?",
        "Você compartilha conteúdos úteis?",
        "O que faz você compartilhar um conteúdo?",
        "O que faz você comentar?",
        "O que faz você voltar para um criador?",
        "Você acompanha mais pessoas ou marcas?",
        "O que faz alguém parecer autêntico?",
        "Autenticidade pode ser planejada?",
        "Você acha que criador precisa mostrar vulnerabilidade?",
        "Bastidores aproximam o público?",
        "Você acha que storytelling funciona para qualquer nicho?",
        "Uma história pessoal pode ensinar algo?",
        "Você usaria humor no seu conteúdo?",
        "Todo nicho pode criar conteúdo divertido?",
        "Você acha que tendências ajudam criadores?",
        "Você entraria em uma trend sem adaptá-la?",
        "Você acha que trends deixam criadores iguais?",
        "Você prefere conteúdo curto ou longo?",
        "Um minuto é suficiente para explicar algo?",
        "Você assistiria um vídeo de 10 minutos?",
        "Você acha que legenda ainda importa?",
        "Você revisa seu conteúdo antes de publicar?",
        "Você apagaria um conteúdo que flopou?",
        "Um conteúdo com poucas views pode ser bom?",
        "Você mede seus resultados ou só olha visualizações?",
        "Qual métrica mais importa para um criador?",
        "Você criaria conteúdo mesmo sem ganhar dinheiro?",
        "Você continuaria criando se ninguém curtisse?",
        "O que faria você desistir de criar?",
        "O que faria você continuar criando?",
        "Qual assunto você falaria por uma hora?",
        "O que você gostaria de ensinar para alguém?",
        "Qual opinião sua renderia uma boa conversa?",
      ],
    },
    autoconhecimento: {
      "Treino & Academia": [
        "Treinar cedo realmente faz diferença?",
        "Você prefere treinar de manhã ou à noite?",
        "Qual exercício você mais gosta?",
        "Qual exercício você odeia?",
        "Você treinaria todos os dias?",
        "Descanso também faz parte do treino?",
        "Você acha que cardio é indispensável?",
        "Musculação é melhor que cardio?",
        "Treino curto pode funcionar?",
        "Você prefere treinos rápidos ou longos?",
        "O que mais te motiva a treinar?",
        "Música melhora seu treino?",
        "Você treina mesmo sem vontade?",
        "Disciplina vence a motivação?",
        "Treinar em casa funciona?",
        "Academia ou treino em casa?",
        "Você usaria um personal trainer?",
        "Personal realmente faz diferença?",
        "Você acha academia intimidante?",
        "O que torna uma academia confortável?",
        "Você já desistiu de treinar?",
        "Por que é tão difícil manter uma rotina?",
        "Você prefere treinar sozinho ou acompanhado?",
        "Treinar com amigos ajuda?",
        "Você acha que treino precisa ser divertido?",
        "Você treinaria só pelo resultado estético?",
        "Saúde ou estética: qual seu maior motivador?",
        "Você acha que academia mudou sua autoestima?",
        "O corpo muda sua relação com roupas?",
        "Você acompanha seu progresso como?",
        "Peso é uma boa métrica de evolução?",
        "Espelho ou balança: qual você prefere?",
        "Você tiraria fotos para acompanhar evolução?",
        "Treino precisa doer para funcionar?",
        "Suor significa treino eficiente?",
        "Você acha que existe treino perfeito?",
        "Quanto tempo leva para criar consistência?",
        "Você mudaria seu treino frequentemente?",
        "O mesmo treino pode funcionar por muito tempo?",
        "Você pesquisa exercícios antes de fazer?",
        "Você confia em dicas fitness da internet?",
        "Influenciadores fitness ajudam ou atrapalham?",
        "Você já caiu em algum mito fitness?",
        "Qual mito fitness mais te irrita?",
        "Pré-treino realmente vale a pena?",
        "Alongamento antes do treino é necessário?",
        "Você prefere máquinas ou pesos livres?",
        "Treino de perna: ama ou odeia?",
        "Você faria uma aula coletiva?",
        "Qual modalidade você gostaria de experimentar?",
        "Corrida é para todo mundo?",
        "Você acha que caminhar conta como exercício?",
        "Treinar em jejum funciona para você?",
        "O que mais atrapalha sua constância?",
      ],
      "Lifestyle": [
        "O que significa ter qualidade de vida?",
        "Você prefere rotina ou espontaneidade?",
        "Como seria seu dia perfeito?",
        "Você acorda cedo porque gosta ou precisa?",
        "Você acha que manhãs produtivas são superestimadas?",
        "Você consegue ficar sem celular por um dia?",
        "Quanto tempo de tela é demais?",
        "Você acha que redes sociais melhoram sua vida?",
        "Como você organiza seu dia?",
        "Você usa agenda ou vai no improviso?",
        "Você é uma pessoa organizada?",
        "Casa organizada muda seu humor?",
        "Minimalismo funciona na vida real?",
        "Você compraria menos se tivesse menos opções?",
        "Você prefere morar sozinho ou acompanhado?",
        "O que torna uma casa aconchegante?",
        "Você gosta de cozinhar em casa?",
        "Comer fora é lazer ou necessidade?",
        "Você prefere viajar ou ficar em casa?",
        "Viajar sozinho é libertador ou assustador?",
        "Qual viagem você faria novamente?",
        "Você planeja viagens ou improvisa?",
        "Experiências ou coisas materiais?",
        "Você acha que dinheiro compra qualidade de vida?",
        "O que vale a pena pagar mais caro?",
        "O que você parou de comprar?",
        "Você acha que consumo virou entretenimento?",
        "Você compra por necessidade ou desejo?",
        "Como você decide o que comprar?",
        "Você consegue guardar dinheiro?",
        "O que significa uma vida confortável?",
        "Você acha que produtividade virou obsessão?",
        "Descansar sem culpa é possível?",
        "Você se considera uma pessoa produtiva?",
        "Multitarefa realmente funciona?",
        "Você consegue fazer uma coisa por vez?",
        "Rotina matinal funciona mesmo?",
        "Rotina noturna faz diferença?",
        "Você dorme o suficiente?",
        "O celular atrapalha seu sono?",
        "Você tem algum hábito que mudou sua vida?",
        "Qual hábito você gostaria de abandonar?",
        "Qual hábito gostaria de construir?",
        "Você acha que pequenos hábitos transformam a rotina?",
        "O que deixa seu dia mais leve?",
        "Você prioriza lazer na rotina?",
        "Você acha que hobbies são necessários?",
        "Qual hobby você gostaria de começar?",
        "Você consegue aproveitar momentos sem registrar?",
        "Você vive o momento ou pensa no próximo?",
        "Você acha que desacelerar virou luxo?",
        "O que você faria com um dia totalmente livre?",
        "Você prefere uma vida previsível ou intensa?",
        "Qual escolha deixou sua vida melhor?",
      ],
      "Alimentação": [
        "Você realmente precisa tomar café da manhã?",
        "Qual refeição você mais gosta?",
        "Você cozinha ou pede comida?",
        "Comer saudável precisa ser caro?",
        "Você acha que dieta precisa ser complicada?",
        "Qual alimento você nunca enjoa?",
        "Você experimentaria um alimento diferente?",
        "Você lê os rótulos dos alimentos?",
        "O que você procura em um rótulo?",
        "Alimentos “fit” são realmente melhores?",
        "Você confia em produtos com embalagem saudável?",
        "Low carb funciona para todo mundo?",
        "Você acha que carboidrato virou vilão?",
        "Glúten faz mal para todo mundo?",
        "Açúcar é realmente o grande vilão?",
        "Você reduziria açúcar no dia a dia?",
        "Você prefere doce ou salgado?",
        "Qual comida lembra sua infância?",
        "Comida afetiva influencia suas escolhas?",
        "Você acha que comida também é memória?",
        "Você come por fome ou vontade?",
        "Você reconhece quando está satisfeito?",
        "Comer assistindo televisão muda sua alimentação?",
        "Você costuma beliscar durante o dia?",
        "Você planeja suas refeições?",
        "Marmita facilita a rotina?",
        "Você acha marmita sem graça?",
        "Qual comida você sempre pede no delivery?",
        "Delivery facilita ou atrapalha sua alimentação?",
        "Você acha que comer fora dificulta hábitos saudáveis?",
        "Restaurante saudável precisa ser caro?",
        "Você escolheria sabor ou saúde?",
        "É possível comer bem sem abrir mão do prazer?",
        "Você acha que existe comida proibida?",
        "“Dia do lixo” faz sentido?",
        "Você acredita em dieta sem sofrimento?",
        "Qual dieta você jamais faria?",
        "Você já tentou alguma dieta da moda?",
        "Por que dietas da moda viralizam?",
        "Suplementos são realmente necessários?",
        "Você compraria um suplemento viral?",
        "Você pesquisa antes de comprar alimentos?",
        "Você acredita em receitas virais?",
        "Qual receita viral você testaria?",
        "Air fryer realmente mudou a alimentação?",
        "Você acha que cozinhar deveria ser ensinado na escola?",
        "Educação alimentar deveria começar na infância?",
        "Você acha que sabemos escolher alimentos?",
        "Qual mito alimentar mais te irrita?",
        "Água com limão realmente faz diferença?",
        "Você acredita em alimentos que “desinflamam”?",
        "Alimentação influencia energia?",
        "O que você mudaria na sua alimentação?",
        "Qual hábito alimentar você gostaria de melhorar?",
      ],
      "Profissão": [
        "Você gosta do que trabalha?",
        "Trabalho precisa trazer propósito?",
        "Você escolheria dinheiro ou realização?",
        "Você trabalharia em algo que ama por menos dinheiro?",
        "Home office realmente melhorou sua vida?",
        "Você prefere presencial ou remoto?",
        "Trabalho híbrido é o melhor dos mundos?",
        "Você consegue separar trabalho e vida pessoal?",
        "Você trabalha melhor sozinho ou em equipe?",
        "Você prefere estabilidade ou liberdade?",
        "Você pediria um aumento hoje?",
        "O que impede pessoas de pedirem aumento?",
        "Você acha importante negociar salário?",
        "Você fala seu salário com amigos?",
        "Transparência salarial ajudaria?",
        "Você mudaria de emprego por um salário maior?",
        "O que faz você permanecer em uma empresa?",
        "Benefícios valem mais que salário?",
        "Você aceitaria menos dinheiro por qualidade de vida?",
        "Você acha que carreira precisa ter planejamento?",
        "Você tem um plano de carreira?",
        "É possível mudar de profissão depois dos 30?",
        "Você faria uma transição de carreira?",
        "Faculdade ainda é indispensável?",
        "Você faria uma faculdade hoje?",
        "Cursos online substituem faculdade?",
        "Networking é realmente importante?",
        "Você sabe fazer networking?",
        "Você pediria ajuda profissionalmente?",
        "Você acha que indicação pesa mais que currículo?",
        "Currículo ainda importa?",
        "LinkedIn realmente ajuda na carreira?",
        "Você posta sobre seu trabalho nas redes?",
        "Você mostraria seus bastidores profissionais?",
        "Marca pessoal é importante para qualquer profissão?",
        "Você se considera uma autoridade na sua área?",
        "Como você demonstra que sabe o que faz?",
        "Você acha que especialização limita oportunidades?",
        "Generalista ou especialista: qual você escolheria?",
        "Você aceitaria trabalhar por conta própria?",
        "Empreender é liberdade ou pressão?",
        "Você abriria um negócio sozinho?",
        "Você acha que todo mundo deveria empreender?",
        "Freelancer ou CLT: qual escolheria?",
        "Você teria coragem de largar seu emprego?",
        "O que faria você pedir demissão?",
        "Você acha que produtividade virou cobrança?",
        "Trabalhar muito significa produzir mais?",
        "Você consegue dizer não no trabalho?",
        "Você já recusou uma oportunidade por medo?",
        "Errar no trabalho pode ajudar na carreira?",
        "Você acha que chefe bom faz diferença?",
        "O que define uma boa liderança?",
        "Você prefere líder exigente ou acolhedor?",
        "Você acha que ambiente pesa mais que salário?",
        "Qual conselho profissional você gostaria de ter recebido?",
      ],
    }
  }
};
