// Banco-semente de temas das categorias fixas.
// Estrutura: TEMAS.categoriasFixas.pesquisa (assunto solto) e
// TEMAS.categoriasFixas.autoconhecimento (frase-instrução) — ver CLAUDE.md R13.
var TEMAS = {
  categoriasFixas: {
    pesquisa: {
      "Moda": [
        "O new look de Christian Dior",
        "A ascensão e queda do fast fashion",
        "Coco Chanel e a libertação do corpo feminino na moda",
        "O movimento punk e sua estética de moda",
        "A história do jeans",
        "Alexander McQueen e a moda como performance",
        "O renascimento dos anos 2000 (Y2K) nas passarelas atuais",
        "A moda sustentável e o slow fashion",
        "O impacto do streetwear na alta-costura",
        "Yves Saint Laurent e o terno feminino",
        "A estética normcore",
        "O balé russo e sua influência na moda do início do século 20",
        "A cultura das sneakers e seu mercado de revenda",
        "O corset através dos séculos",
        "A moda genderless e a quebra de padrões binários",
        "O legado de Vivienne Westwood",
        "A haute couture francesa e seus rituais",
        "O movimento grunge nos anos 90",
        "A moda como ferramenta política nos anos 60",
        "O uniforme escolar japonês e sua influência global",
        "A ascensão das lojas de segunda mão (thrift) entre jovens",
        "O impacto das redes sociais nas semanas de moda",
        "A silhueta power dressing dos anos 80",
        "O kimono e sua reinterpretação na moda ocidental",
        "A moda afro-brasileira e seus símbolos",
        "O fenômeno das colaborações entre marcas de luxo e streetwear",
        "A estética do quiet luxury",
        "O impacto da Vogue na formação do gosto popular",
        "A moda drag e sua estética de exagero",
        "O renascimento do crochê e do artesanal na moda contemporânea",
        "A cultura dos desfiles de rua em São Paulo",
        "O papel dos acessórios como símbolo de status",
        "A moda militar e sua reapropriação civil",
        "O minimalismo escandinavo na moda",
        "A moda como identidade em subculturas urbanas",
        "O impacto do TikTok nas microtendências de moda",
        "A reinvenção do terninho feminino no mundo corporativo",
        "A moda gótica e suas raízes na literatura romântica",
        "O boom das marcas nativas digitais",
        "A relação entre moda e clima nas coleções sazonais",
        "O legado de Tom Ford na Gucci",
        "A cultura dos brechós de luxo",
        "O impacto ambiental da indústria têxtil",
        "A moda como resistência em contextos de censura",
        "O fenômeno dos personal stylists nas redes sociais",
        "A volta do salto plataforma",
        "A moda no cinema como construção de personagem",
        "O consumo consciente e a moda cápsula",
        "A ascensão das marcas latino-americanas no cenário internacional",
        "O papel das celebridades como it girls da moda",
        "A moda através das gerações: o que muda entre pais e filhos",
        "O impacto do algoritmo nas escolhas de estilo pessoal",
        "A cultura do outfit do dia nas redes sociais",
        "A moda como linguagem não verbal",
        "O renascimento dos tecidos naturais",
        "A moda plus size e sua representatividade na indústria",
        "O legado das grandes casas de moda italianas",
        "A relação entre moda e status social ao longo da história",
        "O futuro dos tecidos inteligentes e da moda tecnológica",
        "A moda como forma de contar a própria história pessoal"
      ],
      "Beleza": [
        "A história do batom vermelho",
        "O movimento skinimalism no skincare",
        "A ascensão dos ingredientes ativos (retinol, ácidos, vitamina C)",
        "O impacto dos filtros de redes sociais na autoimagem",
        "A cultura K-beauty e sua rotina de dez passos",
        "O boom dos preenchimentos faciais entre jovens adultos",
        "A história da maquiagem drag",
        "O movimento no makeup makeup",
        "A ascensão das marcas de beleza inclusivas em tons de pele",
        "O papel dos dermatologistas influenciadores digitais",
        "A cultura do cabelo natural e o movimento crespo/cacheado",
        "O boom dos perfumes de nicho",
        "A história do rímel e das pestanas postiças",
        "O fenômeno da beleza clean girl",
        "A relação entre beleza e envelhecimento na publicidade",
        "O impacto da IA generativa em campanhas de beleza",
        "A cultura das unhas como forma de expressão artística",
        "O movimento body positive e sua chegada à indústria de beleza",
        "A ascensão dos protetores solares como rotina obrigatória",
        "A história das sobrancelhas através das décadas",
        "O boom dos tratamentos capilares caseiros (slow hair)",
        "A cultura da beleza masculina e o crescimento do skincare para homens",
        "O papel das celebridades como donas de marcas de beleza",
        "A relação entre maquiagem e identidade de gênero",
        "O fenômeno dos get ready with me nas redes sociais",
        "A história do esmalte e da manicure profissional",
        "O boom da beleza biohacking (suplementos, colágeno, longevidade)",
        "A cultura da beleza asiática e sua influência global",
        "O impacto da mídia nos padrões de beleza ao longo das décadas",
        "A ascensão dos produtos de beleza sustentáveis e refis",
        "A história da tatuagem como expressão de beleza e identidade",
        "O papel da beleza na autoestima em contextos terapêuticos",
        "O fenômeno do glass skin",
        "A cultura das cirurgias plásticas nas redes sociais",
        "O boom dos óleos capilares e tratamentos ayurvédicos",
        "A relação entre beleza e maternidade e as mudanças no corpo",
        "A ascensão da micropigmentação e da maquiagem definitiva",
        "O papel da beleza em rituais culturais e religiosos",
        "A cultura da beleza vegana e cruelty-free",
        "O impacto das câmeras frontais dos celulares na indústria de beleza",
        "A história do salão de beleza como espaço social",
        "O boom dos dupes, versões baratas de produtos de luxo",
        "A relação entre beleza e envelhecimento saudável",
        "A ascensão das rotinas de beleza noturnas",
        "O papel da beleza em terapias de autocuidado mental",
        "A cultura da beleza indígena brasileira",
        "O fenômeno da beleza mob wife aesthetic",
        "A história da depilação através dos séculos",
        "O boom dos tratamentos de beleza a laser",
        "A relação entre beleza e status econômico",
        "A ascensão dos influenciadores de beleza masculina",
        "O papel da beleza na construção de personagens no cinema",
        "A cultura da beleza natural versus beleza artificial",
        "O fenômeno dos rituais de beleza coreanos em casa",
        "A história do uso de perucas e extensões capilares",
        "O boom da beleza personalizada por IA (diagnóstico de pele)",
        "A relação entre beleza e bem-estar emocional",
        "A ascensão da beleza old money aesthetic",
        "O papel da beleza em cerimônias de casamento pelo mundo",
        "A cultura da beleza regenerativa e dos procedimentos não invasivos"
      ],
      "Entretenimento": [
        "O fenômeno dos reality shows de confinamento",
        "A ascensão dos podcasts como novo formato de entretenimento",
        "O impacto do streaming no fim da TV aberta",
        "A cultura dos late night shows americanos",
        "O boom dos true crime documentários",
        "A história dos programas de auditório no Brasil",
        "O fenômeno das dragqueens no entretenimento mainstream",
        "A ascensão dos creators como substitutos de celebridades tradicionais",
        "O impacto do algoritmo do TikTok na indústria do entretenimento",
        "A cultura das convenções (comic cons) pelo mundo",
        "O boom das séries de comédia de stand-up",
        "A história dos game shows e sua evolução",
        "O fenômeno dos crossovers entre universos de entretenimento",
        "A ascensão do entretenimento ao vivo (lives) durante e após a pandemia",
        "O impacto das plataformas de streaming de áudio no consumo de rádio",
        "A cultura dos fandoms organizados",
        "O boom dos programas de competição culinária",
        "A história do circo como forma de entretenimento popular",
        "O fenômeno das novelas e seu declínio de audiência",
        "A ascensão dos shows de mágica e ilusionismo no streaming",
        "O impacto da inteligência artificial na criação de roteiros",
        "A cultura dos escape rooms como entretenimento social",
        "O boom do entretenimento imersivo (teatro imersivo, experiências)",
        "A história dos parques temáticos e sua evolução",
        "O fenômeno dos vídeos de unboxing e reviews",
        "A ascensão dos jogos de tabuleiro modernos como entretenimento familiar",
        "O impacto do humor de internet (memes) no entretenimento tradicional",
        "A cultura das batalhas de rima e do freestyle",
        "O boom dos ASMR e conteúdos de relaxamento",
        "A história dos musicais e sua adaptação para o cinema",
        "O fenômeno dos programas de matchmaking e encontros",
        "A ascensão do wrestling (WWE) como entretenimento de massa",
        "O impacto das redes sociais na vida dos ex-participantes de reality shows",
        "A cultura dos festivais de música ao vivo",
        "O boom do entretenimento baseado em nostalgia (reboots e remakes)",
        "A história do teatro de revista no Brasil",
        "O fenômeno dos vídeos de day in my life",
        "A ascensão do humor ácido e da comédia de observação",
        "O impacto econômico da indústria do entretenimento em cidades-sede de eventos",
        "A cultura das rádios comunitárias e sua resistência",
        "O boom das experiências de realidade virtual como entretenimento",
        "A história dos animadores de auditório e apresentadores clássicos",
        "O fenômeno dos podcasts de conversa longa (long-form)",
        "A ascensão do entretenimento baseado em jogos de apostas online",
        "O impacto do humor político na TV e no streaming",
        "A cultura dos shows de talentos e suas fórmulas de sucesso",
        "O boom dos conteúdos de slow tv, transmissões lentas e contemplativas",
        "A história das rádios de auditório nos anos 50 e 60",
        "O fenômeno das lives de jogos (gaming) como entretenimento de massa",
        "A ascensão do entretenimento sonoro (audiobooks e ficções em áudio)",
        "O impacto das plataformas internacionais no consumo local de entretenimento",
        "A cultura dos clubes de comédia stand-up",
        "O boom do entretenimento para pets, conteúdo feito para cães assistirem",
        "A história dos concursos de beleza e sua relevância hoje",
        "O fenômeno do entretenimento baseado em desafios virais",
        "A ascensão dos shows de ilusionismo mentalista",
        "O impacto do metaverso nas promessas e fracassos do entretenimento digital",
        "A cultura das maratonas de séries (binge watching)",
        "O boom dos formatos curtos (shorts, reels) substituindo formatos longos",
        "A história do entretenimento circense itinerante no interior do Brasil"
      ],
      "Cultura Pop": [
        "O fenômeno fandom do K-pop no Ocidente",
        "A ascensão dos universos cinematográficos compartilhados",
        "O impacto do meme como linguagem cultural",
        "A cultura das reações e do hate watching",
        "O boom dos remakes de desenhos dos anos 90 e 2000",
        "A história do boy band e girl group como fenômeno cultural",
        "O fenômeno das teorias de fã sobre finais de séries",
        "A ascensão das celebridades que nasceram na internet",
        "O impacto da nostalgia dos anos 2000 na cultura atual",
        "A cultura dos spoilers e como ela mudou o consumo de mídia",
        "O boom dos crossovers entre jogos, filmes e séries",
        "A história dos ícones pop que se tornaram símbolos de uma geração",
        "O fenômeno das guerras de fandom nas redes sociais",
        "A ascensão do humor absurdo e do brainrot como estética",
        "O impacto das plataformas de streaming na formação do cânone pop",
        "A cultura das paródias e remixes virais",
        "O boom das biografias musicais no cinema",
        "A história dos ídolos teen e sua efemeridade",
        "O fenômeno da estética cottagecore e outras microestéticas de internet",
        "A ascensão dos podcasts de cultura pop e crítica de entretenimento",
        "O impacto das celebridades como formadoras de opinião política",
        "A cultura do ship, relacionamentos fictícios criados por fãs",
        "O boom dos jogos retrô e da nostalgia gamer",
        "A história dos super-heróis como mitologia moderna",
        "O fenômeno das dancinhas virais e sua origem",
        "A ascensão da cultura do reboot em Hollywood",
        "O impacto da cultura pop asiática no mundo ocidental",
        "A cultura dos concertos como experiência coletiva pós-pandemia",
        "O boom das teorias da conspiração dentro da cultura pop",
        "A história dos ícones queer na cultura pop mainstream",
        "O fenômeno da cancel culture e seus efeitos sobre celebridades",
        "A ascensão dos criadores de conteúdo como substitutos de estúdios tradicionais",
        "O impacto do TikTok em relançar músicas antigas nas paradas",
        "A cultura das convenções e cosplay como expressão de identidade",
        "O boom dos true crime na cultura pop",
        "A história do videoclipe como forma de arte",
        "O fenômeno das celebridades que se tornam memes",
        "A ascensão da cultura de stan e o fanatismo por artistas",
        "O impacto das redes sociais na vida útil de uma tendência",
        "A cultura pop dos anos 80 e sua influência estética hoje",
        "O boom dos crossovers musicais entre gêneros distintos",
        "A história dos reality shows de celebridades",
        "O fenômeno das queens e kings da internet",
        "A ascensão da estética Y2K entre a geração Z",
        "O impacto da inteligência artificial na criação de celebridades virtuais",
        "A cultura das paradas de música e sua relevância hoje",
        "O boom dos documentários sobre bastidores de artistas pop",
        "A história das bonecas e brinquedos como fenômeno de cultura pop",
        "O fenômeno da estética dark academia",
        "A ascensão dos vilões carismáticos na cultura pop",
        "O impacto das novelas turcas e coreanas no público brasileiro",
        "A cultura do guilty pleasure no consumo de entretenimento",
        "O boom das trilhas sonoras que se tornam fenômenos culturais",
        "A história dos ícones fashion da cultura pop",
        "O fenômeno da estética gremlin core e suas variações",
        "A ascensão de memes que se tornaram produtos comerciais",
        "O impacto da cultura pop latina no mercado internacional",
        "A cultura dos easter eggs em filmes e séries",
        "O boom das paródias de super-heróis",
        "A história da cultura pop como espelho da sociedade de cada década"
      ],
      "Música": [
        "O impacto do streaming na forma como consumimos álbuns",
        "A ascensão do funk brasileiro como fenômeno global",
        "A história do samba e sua resistência cultural",
        "O boom dos artistas independentes fora das gravadoras",
        "A cultura dos shows tributo e das bandas cover",
        "O fenômeno das colaborações entre gêneros musicais opostos",
        "A ascensão do sertanejo universitário e sua transformação",
        "O impacto da inteligência artificial na composição musical",
        "A história do rock brasileiro nos anos 80",
        "O boom do lo-fi como trilha sonora do trabalho remoto",
        "A cultura dos batalhões de rima e do rap de rua",
        "O fenômeno dos artistas que viralizam antes de serem descobertos",
        "A ascensão da música gospel no mainstream",
        "O impacto das playlists algorítmicas no gosto musical das pessoas",
        "A história do MPB como movimento de resistência política",
        "O boom do reggaeton e sua influência na música latina",
        "A cultura dos DJs de festa como headliners de festivais",
        "O fenômeno das músicas que voltam a ser hit décadas depois",
        "A ascensão do trap brasileiro",
        "O impacto da pirataria histórica na indústria musical",
        "A história do axé music e sua economia no Nordeste",
        "O boom da música clássica em versões remixadas para redes sociais",
        "A cultura dos festivais de música independente",
        "O fenômeno dos artistas que produzem tudo sozinhos em casa",
        "A ascensão da música eletrônica brasileira no cenário internacional",
        "O impacto dos vinis e do retorno do formato físico",
        "A história do frevo e do carnaval como expressão musical",
        "O boom das bandas de garagem e do rock alternativo local",
        "A cultura das batidas automáticas e da produção musical por software",
        "O fenômeno dos hinos de torcida e sua identidade musical",
        "A ascensão da música indígena brasileira contemporânea",
        "O impacto dos concertos em realidade virtual",
        "A história do jazz e sua chegada ao Brasil",
        "O boom da música cristã contemporânea entre jovens",
        "A cultura das lives musicais durante a pandemia",
        "O fenômeno das músicas criadas especificamente para viralizar",
        "A ascensão do piseiro e sua origem regional",
        "O impacto da música na publicidade e no branding",
        "A história dos festivais de Woodstock e sua herança cultural",
        "O boom da música instrumental para estudo e concentração",
        "A cultura do vinil colecionável entre jovens",
        "O fenômeno das bandas que se reencontram após décadas",
        "A ascensão da música afro-brasileira contemporânea",
        "O impacto do TikTok na criação de hits musicais",
        "A história da bossa nova e sua exportação cultural",
        "O boom dos remixes de música clássica com eletrônica",
        "A cultura dos shows acústicos e formatos intimistas",
        "O fenômeno das músicas-tema de novelas e sua permanência",
        "A ascensão do k-pop como indústria organizada de música pop",
        "O impacto da música nas manifestações políticas brasileiras",
        "A história do forró e sua modernização",
        "O boom das batalhas de covers nas redes sociais",
        "A cultura dos setlists e da expectativa em torno de shows",
        "O fenômeno das músicas proibidas ou censuradas em diferentes épocas",
        "A ascensão da música gaúcha regional",
        "O impacto dos aplicativos de karaokê caseiro",
        "A história da ópera e sua popularização em versões modernas",
        "O boom da música afro-latina no mercado americano",
        "A cultura dos festivais universitários de música",
        "A relação entre música e memória afetiva"
      ],
      "Livros": [
        "O boom do romantasy nas livrarias",
        "A ascensão do booktok como motor de vendas",
        "A história dos clubes de leitura e sua volta às redes sociais",
        "O impacto dos audiobooks no hábito de leitura",
        "A cultura dos livros de autoajuda e sua crítica recorrente",
        "O fenômeno das distopias jovens adultas",
        "A ascensão da literatura de fantasia brasileira",
        "O impacto das adaptações de livros para streaming",
        "A história da censura literária no Brasil",
        "O boom dos ensaios pessoais e memórias",
        "A cultura dos spoilers em resenhas de livros",
        "O fenômeno dos livros que viralizam por uma única cena",
        "A ascensão da literatura marginal e de periferia",
        "O impacto da autopublicação na indústria editorial",
        "A história dos livros censurados e queimados ao longo do tempo",
        "O boom dos livros de não ficção sobre produtividade",
        "A cultura das feiras literárias e seu papel social",
        "O fenômeno dos unboxing de livros nas redes sociais",
        "A ascensão dos escritores independentes que viraram best-sellers",
        "O impacto da inteligência artificial na escrita de ficção",
        "A história do romance policial e sua evolução",
        "O boom da literatura de terror contemporânea",
        "A cultura dos diários e cadernos de escrita pessoal",
        "O fenômeno dos livros-jogo e narrativas interativas",
        "A ascensão da poesia nas redes sociais",
        "O impacto das bibliotecas públicas na formação de leitores",
        "A história dos livros proibidos em regimes autoritários",
        "O boom da literatura de ficção científica brasileira",
        "A cultura dos clássicos que todo mundo finge ter lido",
        "O fenômeno dos livros que inspiram teorias de fãs",
        "A ascensão da literatura indígena brasileira contemporânea",
        "O impacto do formato e-book no mercado editorial",
        "A história dos pseudônimos literários e seus motivos",
        "O boom das reescritas de mitologia na literatura atual",
        "A cultura das dedicatórias e dos exemplares autografados",
        "O fenômeno dos livros que mudam a vida segundo as redes sociais",
        "A ascensão dos quadrinhos e graphic novels como literatura séria",
        "O impacto das listas de mais vendidos na escolha do leitor",
        "A história da literatura epistolar, romances em cartas",
        "O boom dos livros sobre finanças pessoais",
        "A cultura dos rituais de leitura, onde e quando as pessoas leem",
        "O fenômeno das sagas literárias que nunca terminam",
        "A ascensão da literatura de terror psicológico brasileiro",
        "O impacto das resenhas de influenciadores na venda de livros",
        "A história dos livros que foram best-sellers póstumos",
        "O boom da literatura de crescimento pessoal espiritual",
        "A cultura das anotações e grifos em livros físicos",
        "O fenômeno dos livros baseados em fatos reais e crimes verídicos",
        "A ascensão das antologias de contos como formato popular",
        "O impacto da leitura em voz alta como prática de conexão",
        "A história dos romances russos e sua influência global",
        "O boom das reescritas de fábulas e contos de fadas para adultos",
        "A cultura dos livros de cabeceira e da leitura antes de dormir",
        "O fenômeno dos livros escritos por celebridades",
        "A ascensão da não ficção narrativa, jornalismo literário",
        "O impacto das traduções na percepção de um livro em outro idioma",
        "A história das primeiras edições e do colecionismo de livros raros",
        "O boom dos livros infantis que também falam com adultos",
        "A cultura do did not finish e da permissão para abandonar livros",
        "A relação entre leitura e desenvolvimento da empatia"
      ],
      "Arte": [
        "Mies van der Rohe e o minimalismo na arquitetura",
        "O movimento surrealista e seus símbolos mais famosos",
        "A street art como forma legítima de expressão artística",
        "O impacto de Frida Kahlo na arte latino-americana",
        "A história do barroco brasileiro e o Aleijadinho",
        "O fenômeno da arte generativa criada por algoritmos",
        "A ascensão dos museus digitais e das exposições virtuais",
        "O impacto de Basquiat na arte contemporânea e no mercado de arte",
        "A história do renascimento italiano e seus mestres",
        "O boom da arte NFT e sua efêmera explosão de mercado",
        "A cultura dos grafiteiros brasileiros e seu reconhecimento internacional",
        "O fenômeno da arte performática como crítica social",
        "A ascensão das artistas mulheres historicamente esquecidas pelo cânone",
        "O impacto de Oscar Niemeyer na identidade arquitetônica do Brasil",
        "A história do cubismo e a fragmentação da perspectiva",
        "O boom das instalações imersivas em museus",
        "A cultura dos leilões de arte e seus valores milionários",
        "O fenômeno da arte feita por inteligência artificial",
        "A ascensão do muralismo mexicano e seu papel político",
        "O impacto de Tarsila do Amaral na construção da identidade brasileira",
        "A história da fotografia como forma de arte reconhecida",
        "O boom da arte conceitual e sua provocação ao que é arte",
        "A cultura dos ateliês colaborativos e coletivos artísticos",
        "O fenômeno da arte urbana e sua relação com a gentrificação",
        "A ascensão de artistas indígenas brasileiros na cena contemporânea",
        "O impacto do impressionismo na forma de retratar a luz",
        "A história da escultura clássica grega e sua influência ocidental",
        "O boom das bienais de arte como vitrine internacional",
        "A cultura da arte naïf brasileira",
        "O fenômeno das exposições sensoriais e imersivas de Van Gogh",
        "A ascensão da arte digital e dos softwares de criação",
        "O impacto de Salvador Dalí na cultura pop",
        "A história da arte sacra colonial brasileira",
        "O boom da cerâmica artesanal como movimento de retorno ao manual",
        "A cultura do colecionismo de arte entre novos investidores",
        "O fenômeno das intervenções urbanas temporárias",
        "A ascensão da arte afro-brasileira contemporânea",
        "O impacto de Andy Warhol na relação entre arte e consumo",
        "A história da gravura e da xilogravura popular no Nordeste",
        "O boom dos museus a céu aberto",
        "A cultura dos ready-mades desde Duchamp",
        "O fenômeno da arte como terapia e ferramenta de saúde mental",
        "A ascensão do design de tipografia como expressão artística",
        "O impacto da arte abstrata na quebra da representação figurativa",
        "A história dos vitrais nas catedrais medievais",
        "O boom da arte têxtil e do bordado como manifesto",
        "A cultura dos museus de arte com entrada gratuita",
        "O fenômeno das restaurações polêmicas de obras clássicas",
        "A ascensão da arte queer na cena contemporânea brasileira",
        "O impacto da fotografia de rua na narrativa urbana",
        "A história dos autorretratos como autoanálise artística",
        "O boom da land art e da arte ambiental",
        "A cultura das feiras de arte acessível para novos colecionadores",
        "O fenômeno da arte como denúncia de crises humanitárias",
        "A ascensão dos artistas outsider, sem formação formal",
        "O impacto da arquitetura brutalista nas cidades brasileiras",
        "A história da técnica do fresco na pintura renascentista",
        "O boom das residências artísticas internacionais",
        "A cultura dos museus comunitários em bairros periféricos",
        "A relação entre arte e luto em obras memoriais"
      ],
      "Psicologia": [
        "O conceito de apego e como ele molda relacionamentos adultos",
        "A cultura da terapia como tema recorrente nas redes sociais",
        "O fenômeno da procrastinação e suas raízes emocionais",
        "A ascensão do termo burnout no vocabulário popular",
        "O impacto da comparação social nas redes sobre a autoestima",
        "A história da psicanálise e sua chegada ao Brasil",
        "O conceito de inteligência emocional no ambiente de trabalho",
        "A cultura do autodiagnóstico via internet",
        "O fenômeno da ansiedade social entre jovens adultos",
        "A ascensão da psicologia positiva e da busca por felicidade",
        "O impacto da solidão como questão de saúde pública",
        "A história dos testes de personalidade populares",
        "O conceito de resiliência e seus limites como discurso motivacional",
        "A cultura do gaslighting como termo popularizado",
        "O fenômeno da síndrome do impostor no ambiente profissional",
        "A ascensão da terapia de casal como prática comum",
        "O impacto das telas no desenvolvimento infantil",
        "A história do comportamento de manada e da psicologia de multidões",
        "O conceito de apego evitativo e ansioso nas relações modernas",
        "A cultura da autoajuda e sua promessa de transformação rápida",
        "O fenômeno do medo de ficar de fora",
        "A ascensão da neurociência popular explicando comportamento humano",
        "O impacto do luto não resolvido no comportamento adulto",
        "A história dos experimentos psicológicos éticos e questionáveis",
        "O conceito de limites saudáveis nas relações pessoais",
        "A cultura da validação externa nas redes sociais",
        "O fenômeno da fadiga de decisão no cotidiano moderno",
        "A ascensão da psicologia infantil positiva na criação dos filhos",
        "O impacto do perfeccionismo na saúde mental",
        "A história do movimento antimanicomial no Brasil",
        "O conceito de trauma geracional e como ele se repete em famílias",
        "A cultura da terapia online e dos aplicativos de saúde mental",
        "O fenômeno da procrastinação por medo do fracasso",
        "A ascensão dos estudos sobre neuroplasticidade e mudança de hábitos",
        "O impacto do ciúme e da insegurança nos relacionamentos",
        "A história dos manicômios e da reforma psiquiátrica",
        "O conceito de autossabotagem e seus padrões inconscientes",
        "A cultura do self-care e sua comercialização",
        "O fenômeno do medo de compromisso nas relações contemporâneas",
        "A ascensão da psicologia positiva aplicada ao esporte",
        "O impacto do isolamento social na saúde mental de idosos",
        "A história da terapia cognitivo-comportamental",
        "O conceito de mentalidade de escassez e de abundância",
        "A cultura da meditação e do mindfulness no ocidente",
        "O fenômeno do burnout parental",
        "A ascensão dos estudos sobre o sono e a saúde mental",
        "O impacto das dinâmicas familiares disfuncionais na vida adulta",
        "A história dos rótulos psiquiátricos e sua evolução ao longo do tempo",
        "O conceito de zona de conforto e o medo da mudança",
        "A cultura da comparação entre gerações",
        "O fenômeno da dependência emocional em relacionamentos",
        "A ascensão da psicologia organizacional dentro das empresas",
        "O impacto da criação com pais ausentes emocionalmente",
        "A história do conceito de inconsciente coletivo de Jung",
        "O conceito de autoestima condicional versus incondicional",
        "A cultura da terapia em grupo e dos círculos de apoio",
        "O fenômeno do medo de julgamento social",
        "A ascensão dos estudos sobre empatia e sua importância nas relações",
        "O impacto do humor como mecanismo de defesa psicológico",
        "A relação entre autoconhecimento e tomada de decisões importantes"
      ],
      "Em Alta": [
        "O boom dos aplicativos de IA generativa no dia a dia",
        "A ascensão dos criadores de conteúdo que substituem agências de publicidade",
        "O fenômeno das microtendências que duram poucas semanas",
        "A discussão global sobre regulamentação da inteligência artificial",
        "O crescimento do consumo de conteúdo em áudio (podcasts e audiobooks)",
        "A ascensão econômica dos criadores independentes fora de grandes marcas",
        "O debate sobre jornada de trabalho reduzida em diferentes países",
        "O crescimento das comunidades pagas de assinatura de criadores",
        "A discussão sobre saúde mental no ambiente corporativo",
        "O fenômeno da detox digital como resposta ao excesso de telas",
        "A ascensão do consumo consciente frente à inflação global",
        "O debate sobre trabalho remoto versus retorno ao escritório",
        "O crescimento dos aplicativos de bem-estar financeiro entre jovens",
        "A discussão pública sobre uso de IA na educação",
        "O fenômeno dos microinfluenciadores como formadores de opinião de nicho",
        "A ascensão de novas moedas e formas de pagamento digital",
        "O debate sobre regulamentação de redes sociais para menores de idade",
        "O crescimento do mercado de experiências em vez de produtos",
        "A discussão sobre longevidade e biohacking entre a geração millennial",
        "O fenômeno das cidades de 15 minutos no planejamento urbano",
        "A ascensão do turismo de bem-estar e retiros de desconexão",
        "O debate sobre automação e o futuro de profissões tradicionais",
        "O crescimento das comunidades online baseadas em interesses de nicho",
        "A discussão sobre transparência de marcas nas redes sociais",
        "O fenômeno da economia da atenção e seus efeitos colaterais",
        "A ascensão dos formatos de vídeo curto como principal fonte de notícia",
        "O debate sobre créditos de carbono e consumo sustentável",
        "O crescimento do mercado de jogos como forma de socialização",
        "A discussão sobre inteligência artificial substituindo empregos criativos",
        "O fenômeno do quiet quitting no ambiente de trabalho",
        "A ascensão dos aplicativos de terapia e apoio emocional por chat",
        "O debate sobre a volatilidade das criptomoedas",
        "O crescimento do interesse por autossuficiência e produção de alimentos",
        "A discussão pública sobre desinformação e verificação de fatos",
        "O fenômeno das comunidades de moradia compartilhada (coliving)",
        "A ascensão de marcas que nascem direto nas redes sociais",
        "O debate sobre a ética do uso de dados pessoais por grandes empresas",
        "O crescimento do mercado de suplementação e nutrição personalizada",
        "A discussão sobre o impacto ambiental da inteligência artificial",
        "O fenômeno das plataformas de recomerço, revenda de roupas e eletrônicos",
        "A ascensão de vozes sintéticas e avatares digitais em campanhas de marca",
        "O debate sobre a jornada de quatro dias de trabalho",
        "O crescimento das comunidades de apoio para pais solo",
        "A discussão sobre saúde financeira entre jovens adultos",
        "O fenômeno dos creators que se tornam empresários de mídia",
        "A ascensão de novos formatos de entrevista e conversa longa online",
        "O debate sobre inteligência artificial na produção de música e arte",
        "O crescimento do mercado de bem-estar animal e produtos para pets",
        "A discussão pública sobre burnout entre profissionais de saúde",
        "O fenômeno da nostalgia como estratégia de marketing recorrente",
        "A ascensão de comunidades baseadas em jogos ao vivo (streaming)",
        "O debate sobre privacidade em assistentes de voz e casas inteligentes",
        "O crescimento do interesse por terapias alternativas e integrativas",
        "A discussão sobre o papel das universidades frente a cursos rápidos online",
        "O fenômeno das assinaturas de conteúdo exclusivo por criadores",
        "A ascensão do consumo de notícias por resumos gerados por IA",
        "O debate sobre a saúde mental de crianças e adolescentes nas redes",
        "O crescimento das iniciativas de economia circular entre marcas",
        "A discussão pública sobre o futuro do emprego formal",
        "O fenômeno de comunidades que migram entre redes sociais em busca de espaços mais autênticos"
      ]
    },
    autoconhecimento: {
      "Treino & Academia": [
        "Descreva por 10 minutos como é o seu treino de hoje, passo a passo.",
        "Conte qual foi o exercício mais difícil que você já enfrentou e como superou.",
        "Explique como você decide o que treinar em cada dia da semana.",
        "Fale sobre o primeiro dia em que você entrou numa academia, como foi.",
        "Descreva a diferença entre o seu treino de hoje e o de um ano atrás.",
        "Conte como a atividade física mudou a forma como você se sente no dia a dia.",
        "Explique, como se fosse para um principiante, como fazer o exercício que você mais gosta.",
        "Fale sobre um dia em que você não teve vontade de treinar, mas foi mesmo assim.",
        "Descreva o seu ritual antes de começar um treino.",
        "Conte qual erro de treino você já cometeu e o que aprendeu com ele.",
        "Explique por que você escolheu a modalidade que pratica hoje.",
        "Fale sobre a relação entre o seu treino e o seu sono.",
        "Descreva como você se sente fisicamente logo depois de treinar.",
        "Conte uma meta física que você já alcançou e como chegou lá.",
        "Explique como a alimentação influencia o seu desempenho no treino.",
        "Fale sobre um período em que você parou de treinar e como foi voltar.",
        "Descreva o equipamento ou acessório de treino que você não vive sem.",
        "Conte como é treinar em dias de chuva, calor extremo ou com pouco tempo.",
        "Explique a diferença entre treinar para estética e treinar para saúde, na sua visão.",
        "Fale sobre alguém que te inspirou a começar a se exercitar.",
        "Descreva como você mede o seu progresso além do espelho e da balança.",
        "Conte como foi a primeira vez que você levantou um peso que parecia impossível.",
        "Explique como você lida com dores musculares no dia seguinte ao treino.",
        "Fale sobre a música ou podcast que não pode faltar no seu treino.",
        "Descreva como seria o seu treino ideal, sem limitação de tempo ou lugar.",
        "Conte se você já treinou lesionado e como isso mudou sua rotina.",
        "Explique como você organiza o tempo para treinar numa semana cheia.",
        "Fale sobre a diferença entre treinar sozinho e treinar acompanhado.",
        "Descreva um treino que parecia impossível no começo e hoje é fácil.",
        "Conte como a sua postura ou disposição mudou desde que começou a treinar.",
        "Explique o que te faz continuar treinando nos dias difíceis.",
        "Fale sobre um mito da academia que você já acreditou e depois descobriu ser falso.",
        "Descreva a sensação de terminar um treino puxado.",
        "Conte como você escolhe roupas e tênis para treinar.",
        "Explique como o treino te ajuda, ou não, a lidar com estresse.",
        "Fale sobre a última vez que você mudou de modalidade de exercício e por quê.",
        "Descreva como seria explicar seu treino de hoje para a sua versão de cinco anos atrás.",
        "Conte se você já treinou em outro país ou cidade e como foi diferente.",
        "Explique o papel do aquecimento e do alongamento na sua rotina.",
        "Fale sobre uma pessoa da academia que marcou sua trajetória.",
        "Descreva como o seu corpo mudou desde que você começou a se exercitar com frequência.",
        "Conte sobre um dia em que o treino salvou seu humor.",
        "Explique como você decide quando é hora de descansar em vez de treinar.",
        "Fale sobre o horário do dia em que você prefere treinar e por quê.",
        "Descreva como seria um treino perfeito, do aquecimento ao alongamento final.",
        "Conte se competir, com você mesmo ou com outros, faz parte da sua motivação.",
        "Explique como o seu treino de hoje se conecta com um objetivo maior.",
        "Fale sobre uma vez em que você quase desistiu de treinar de vez.",
        "Descreva a diferença entre a academia que você frequenta hoje e a que você imaginava quando começou.",
        "Conte como amigos ou família reagem à sua rotina de treino.",
        "Explique o que você diria para alguém que quer começar a treinar mas tem medo.",
        "Fale sobre um exercício que você evita e por quê.",
        "Descreva como o seu treino muda dependendo do seu humor no dia.",
        "Conte se você já treinou por vaidade e depois passou a treinar por saúde, ou o contrário.",
        "Explique como você recupera a disposição depois de um treino muito cansativo.",
        "Fale sobre uma conquista física pequena que te deu muito orgulho.",
        "Descreva como seria a sua semana de treinos ideal, dia por dia.",
        "Conte como a idade mudou, ou não, a forma como você treina.",
        "Explique como você equilibra treino intenso com vida social.",
        "Fale sobre o que o treino te ensinou sobre você mesmo que nada mais ensinou."
      ],
      "Lifestyle": [
        "Conte como foi a sua manhã de hoje, do jeito que ela realmente foi.",
        "Descreva como é o seu domingo ideal, do início ao fim.",
        "Fale sobre um hábito pequeno que mudou a sua rotina para melhor.",
        "Explique como você organiza o seu dia quando tem muita coisa para fazer.",
        "Conte sobre o último fim de semana em que você realmente desconectou.",
        "Descreva o cômodo da sua casa onde você se sente mais você mesmo.",
        "Fale sobre uma rotina que você tentou adotar e não conseguiu manter.",
        "Explique como é o seu ritual antes de dormir.",
        "Conte sobre uma mudança de cidade, casa ou bairro que marcou sua vida.",
        "Descreva como seria o seu dia perfeito, sem preocupação com dinheiro ou tempo.",
        "Fale sobre algo que você comprou recentemente e realmente mudou seu dia a dia.",
        "Explique como você lida com dias em que nada sai como planejado.",
        "Conte sobre uma pessoa que mora com você e como é a rotina em conjunto.",
        "Descreva como o seu estilo de vida mudou nos últimos cinco anos.",
        "Fale sobre um lugar da sua cidade que faz parte da sua rotina sem ser óbvio.",
        "Explique como você equilibra trabalho, descanso e lazer numa semana normal.",
        "Conte sobre uma viagem curta que mudou sua forma de ver o cotidiano.",
        "Descreva como é o seu ritual de organização da casa ou do quarto.",
        "Fale sobre um aplicativo ou ferramenta que você usa todos os dias sem perceber.",
        "Explique como as estações do ano mudam a sua rotina.",
        "Conte sobre uma vez em que você simplificou sua vida ao se desfazer de coisas.",
        "Descreva como seria a sua semana se você não precisasse trabalhar.",
        "Fale sobre um ritual de fim de semana que você não abre mão.",
        "Explique como é dividir tarefas domésticas na sua casa.",
        "Conte sobre um momento do dia que é só seu, sem ninguém por perto.",
        "Descreva como a tecnologia entrou, ou saiu, da sua rotina nos últimos anos.",
        "Fale sobre uma tradição de família que você mantém até hoje.",
        "Explique como você decide onde e como vai gastar seu tempo livre.",
        "Conte sobre uma mudança de rotina causada por uma nova fase da vida.",
        "Descreva o seu bairro para alguém que nunca esteve lá.",
        "Fale sobre como é o seu convívio com vizinhos.",
        "Explique como você cuida de plantas, animais ou de qualquer coisa viva na sua rotina.",
        "Conte sobre um passeio simples que se tornou parte da sua semana.",
        "Descreva como seria um dia sem nenhum compromisso marcado.",
        "Fale sobre a diferença entre a sua rotina de trabalho e a de casa.",
        "Explique como você lida com bagunça e organização no seu espaço.",
        "Conte sobre uma compra que você se arrepende até hoje.",
        "Descreva como você recarrega as energias depois de uma semana cheia.",
        "Fale sobre um costume seu que as pessoas acham estranho.",
        "Explique como é a sua relação com o silêncio e a solidão no dia a dia.",
        "Conte sobre uma amizade que faz parte da sua rotina, mesmo à distância.",
        "Descreva como seria mudar de vida completamente por um mês.",
        "Fale sobre um ritual matinal que você recomendaria para qualquer pessoa.",
        "Explique como você decide o que vale a pena gastar dinheiro no seu estilo de vida.",
        "Conte sobre uma mudança pequena na casa que trouxe grande impacto no seu humor.",
        "Descreva como a sua relação com redes sociais mudou o seu cotidiano.",
        "Fale sobre como é a sua rotina em dias de chuva.",
        "Explique o que te faz sentir produtivo, mesmo em dias mais lentos.",
        "Conte sobre um hobby que ocupa parte do seu tempo livre hoje.",
        "Descreva como seria contar seu dia inteiro em uma única frase.",
        "Fale sobre como você lida com imprevistos que mudam seus planos.",
        "Explique como é organizar as finanças pessoais no seu dia a dia.",
        "Conte sobre um lugar da sua casa que você gostaria de mudar.",
        "Descreva como o clima da sua cidade influencia o seu humor e sua rotina.",
        "Fale sobre como você celebra pequenas conquistas do dia a dia.",
        "Explique o que qualidade de vida significa pra você, na prática.",
        "Conte sobre um momento em que você desacelerou de propósito.",
        "Descreva como seria explicar a sua rotina para alguém de outra geração.",
        "Fale sobre um costume da sua infância que você mantém até hoje.",
        "Explique como você decide quando é hora de descansar de verdade."
      ],
      "Alimentação": [
        "Fale por 10 minutos sobre o que você comeu essa semana e por quê.",
        "Conte qual foi a última vez que você cozinhou algo novo e como foi.",
        "Descreva a refeição que mais te lembra a sua infância.",
        "Explique como é o seu ritual de fazer compras de mercado.",
        "Fale sobre um prato que você faz de olhos fechados, sem receita.",
        "Conte sobre uma vez em que uma receita deu errado e o que aconteceu.",
        "Descreva como é a sua relação com café, chá ou outra bebida do dia a dia.",
        "Explique como a sua alimentação muda dependendo do seu humor.",
        "Fale sobre uma comida que você adorava e não come mais.",
        "Conte sobre um restaurante ou lanchonete que marcou uma fase da sua vida.",
        "Descreva como é organizar as refeições da semana quando a rotina é cheia.",
        "Explique a diferença entre como você comia há dez anos e como come hoje.",
        "Fale sobre um ingrediente que você sempre tem em casa e nunca falta.",
        "Conte sobre a primeira vez que você cozinhou para outra pessoa.",
        "Descreva como é comer sozinho versus comer acompanhado, na sua rotina.",
        "Explique como surgiu algum hábito alimentar que você tem hoje.",
        "Fale sobre uma comida de conforto que você recorre em dias difíceis.",
        "Conte sobre uma viagem em que a comida foi a parte mais marcante.",
        "Descreva como é o seu café da manhã ideal.",
        "Explique como você decide entre cozinhar em casa ou pedir comida.",
        "Fale sobre uma restrição ou escolha alimentar que você segue e por quê.",
        "Conte sobre uma receita de família que passa de geração em geração na sua casa.",
        "Descreva como seria um dia de alimentação perfeito, sem se preocupar com nada.",
        "Explique como a sua relação com comida mudou desde que você é adulto.",
        "Fale sobre um alimento que todo mundo gosta e você não suporta.",
        "Conte sobre a última vez que você repetiu o prato porque estava muito bom.",
        "Descreva como é fazer supermercado com fome versus de estômago cheio.",
        "Explique como você organiza sua geladeira e despensa.",
        "Fale sobre uma comida que você tem curiosidade de provar, mas nunca provou.",
        "Conte sobre um doce ou sobremesa que representa um momento especial na sua vida.",
        "Descreva como a estação do ano muda o que você quer comer.",
        "Explique como é cozinhar para alguém que você ama.",
        "Fale sobre uma vez em que você comeu algo completamente diferente do habitual.",
        "Conte sobre a comida que você levaria para uma ilha deserta.",
        "Descreva o cheiro de uma comida que te transporta para outro momento da vida.",
        "Explique como a comida aparece nas celebrações da sua família.",
        "Fale sobre uma dieta ou mudança alimentar que você já tentou seguir.",
        "Conte sobre a última vez que cozinhar virou um momento de terapia para você.",
        "Descreva como é a sua relação com açúcar e doces no dia a dia.",
        "Explique o papel da comida quando você está estressado ou ansioso.",
        "Fale sobre um prato que você associa a uma pessoa específica.",
        "Conte sobre um erro de cozinha que virou piada na sua casa.",
        "Descreva como seria explicar a comida brasileira para alguém de outro país.",
        "Explique como você equilibra praticidade e prazer na hora de comer.",
        "Fale sobre um alimento da sua região que pouca gente de fora conhece.",
        "Conte sobre a última vez que você comeu fora de casa por impulso.",
        "Descreva como é planejar uma refeição para receber visitas.",
        "Explique como mudou a sua relação com carne, vegetais ou algum grupo alimentar.",
        "Fale sobre um prato que você faz para se sentir cuidado.",
        "Conte sobre a comida que representa a sua cidade ou estado.",
        "Descreva como é lidar com fome durante um dia muito ocupado.",
        "Explique o que comer bem significa pra você, na prática.",
        "Fale sobre uma comida que você recusava na infância e hoje adora.",
        "Conte sobre uma vez em que dividir uma refeição criou uma conexão especial.",
        "Descreva como é o seu ritual de organizar marmitas ou refeições para levar.",
        "Explique como a comida aparece nos seus momentos de comemoração pessoal.",
        "Fale sobre uma bebida, com álcool ou não, que tem uma história por trás para você.",
        "Conte sobre a última receita que você aprendeu vendo alguém cozinhar.",
        "Descreva como seria um jantar ideal com as pessoas que você ama.",
        "Explique o que você gostaria de aprender a cozinhar e ainda não aprendeu."
      ],
      "Profissão": [
        "Descreva por 10 minutos o que você faz no seu trabalho todos os dias.",
        "Conte como foi o seu primeiro dia na profissão que você exerce hoje.",
        "Explique, como se fosse para uma criança, o que é o seu trabalho.",
        "Fale sobre uma tarefa do seu trabalho que parece simples mas exige muita habilidade.",
        "Descreva o pior e o melhor dia que você já teve trabalhando.",
        "Conte como você decidiu seguir a carreira que segue hoje.",
        "Explique o que ninguém entende sobre a sua profissão até trabalhar nela.",
        "Fale sobre uma habilidade que você desenvolveu só depois de começar a trabalhar.",
        "Descreva como é o seu ambiente de trabalho, do jeito que ele realmente é.",
        "Conte sobre um cliente, chefe ou colega que marcou sua trajetória profissional.",
        "Explique como a sua profissão mudou nos últimos anos.",
        "Fale sobre um erro no trabalho que te ensinou uma lição importante.",
        "Descreva como é o seu dia de trabalho ideal, do início ao fim.",
        "Conte sobre a primeira vez que você recebeu um elogio pelo seu trabalho.",
        "Explique o que te fez continuar na sua profissão nos momentos difíceis.",
        "Fale sobre uma ferramenta ou equipamento sem o qual você não trabalha.",
        "Descreva como é explicar sua profissão numa festa para quem não conhece a área.",
        "Conte sobre uma decisão profissional que mudou seu rumo de carreira.",
        "Explique como você organiza a sua rotina de trabalho numa semana cheia.",
        "Fale sobre um mito que as pessoas têm sobre a sua profissão.",
        "Descreva como é lidar com prazos e pressão no seu trabalho.",
        "Conte sobre a última vez que você aprendeu algo totalmente novo no trabalho.",
        "Explique como a sua profissão impacta a vida de outras pessoas.",
        "Fale sobre um projeto ou trabalho do qual você tem muito orgulho.",
        "Descreva como seria um dia normal de trabalho contado como uma história.",
        "Conte sobre alguém que te inspirou a escolher a sua área profissional.",
        "Explique quais são as maiores dificuldades da sua profissão hoje.",
        "Fale sobre como o seu trabalho mudou desde que você começou até agora.",
        "Descreva a diferença entre a sua profissão nos bastidores e como as pessoas a imaginam.",
        "Conte sobre uma vez em que você quase desistiu da sua carreira.",
        "Explique como você lida com feedbacks e críticas no trabalho.",
        "Fale sobre uma competência que você gostaria de desenvolver na sua área.",
        "Descreva como é trabalhar em equipe, ou sozinho, na sua profissão.",
        "Conte sobre um cliente ou situação difícil que você conseguiu resolver bem.",
        "Explique o que te motiva a continuar trabalhando na sua área.",
        "Fale sobre uma mudança na tecnologia que impactou diretamente o seu trabalho.",
        "Descreva como seria o dia de trabalho de alguém que nunca fez o que você faz.",
        "Conte sobre uma conquista profissional que representa muito para você.",
        "Explique como você equilibra vida pessoal e profissional na prática.",
        "Fale sobre uma habilidade da sua profissão que poderia ajudar em qualquer área da vida.",
        "Descreva o que você sente no dia em que finaliza um grande projeto.",
        "Conte sobre uma reunião, prova ou entrevista que marcou sua carreira.",
        "Explique como é lidar com a rotina e a repetição no seu trabalho.",
        "Fale sobre um momento em que você teve que aprender rápido para não travar no trabalho.",
        "Descreva como você se vê profissionalmente daqui a cinco anos.",
        "Conte sobre um chefe ou líder que te ensinou algo importante sobre trabalho.",
        "Explique como a sua profissão é vista por fora versus como ela realmente é.",
        "Fale sobre uma tarefa do seu trabalho que você adiaria para sempre se pudesse.",
        "Descreva como é o primeiro contato com um novo cliente ou projeto.",
        "Conte sobre uma vez em que o trabalho em equipe fez toda a diferença.",
        "Explique o que você diria para alguém que está começando na sua área hoje.",
        "Fale sobre como a remuneração influencia, ou não, sua relação com o trabalho.",
        "Descreva o momento do dia em que você se sente mais produtivo no trabalho.",
        "Conte sobre uma vez em que você teve que dizer não no ambiente profissional.",
        "Explique como você lida com dias em que o trabalho parece não ter fim.",
        "Fale sobre uma competência que sua profissão exige e que poucos imaginam.",
        "Descreva como seria explicar sua rotina de trabalho para a sua versão de dez anos atrás.",
        "Conte sobre uma vez em que você teve que se reinventar profissionalmente.",
        "Explique o que sucesso profissional significa pra você hoje.",
        "Fale sobre o que você mais gostaria que as pessoas soubessem sobre a sua profissão."
      ]
    }
  }
};
